"""Data models for Instagram posts."""
from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, Field
from enum import Enum


class PostStatus(str, Enum):
    """Post status enumeration."""
    DRAFT = "draft"
    SCHEDULED = "scheduled"
    PUBLISHED = "published"
    FAILED = "failed"


class PostType(str, Enum):
    """Instagram post type."""
    IMAGE = "image"
    VIDEO = "video"
    CAROUSEL = "carousel"
    REEL = "reel"
    STORY = "story"


class Post(BaseModel):
    """Instagram post model."""
    id: Optional[str] = None
    caption: str
    hashtags: List[str] = Field(default_factory=list)
    media_urls: List[str] = Field(default_factory=list)
    media_type: PostType = PostType.IMAGE
    status: PostStatus = PostStatus.DRAFT
    
    # Scheduling
    scheduled_time: Optional[datetime] = None
    published_time: Optional[datetime] = None
    
    # Instagram IDs
    instagram_post_id: Optional[str] = None
    instagram_media_id: Optional[str] = None
    
    # Analytics
    likes_count: int = 0
    comments_count: int = 0
    shares_count: int = 0
    saves_count: int = 0
    reach: int = 0
    impressions: int = 0
    engagement_rate: float = 0.0
    
    # Metadata
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    
    # Generation metadata
    image_prompt: Optional[str] = None
    content_theme: Optional[str] = None
    
    class Config:
        """Pydantic config."""
        use_enum_values = True
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }
    
    @property
    def full_caption(self) -> str:
        """Get caption with hashtags."""
        hashtag_str = " ".join([f"#{tag}" for tag in self.hashtags])
        return f"{self.caption}\n\n{hashtag_str}".strip()
    
    def calculate_engagement_rate(self, followers_count: int) -> float:
        """Calculate engagement rate."""
        if followers_count == 0:
            return 0.0
        total_engagement = self.likes_count + self.comments_count + self.saves_count
        self.engagement_rate = (total_engagement / followers_count) * 100
        return self.engagement_rate


class ContentIdea(BaseModel):
    """Content idea generated by AI."""
    theme: str
    caption: str
    hashtags: List[str]
    image_prompt: str
    best_posting_time: Optional[str] = None
    target_audience_segment: Optional[str] = None
